MESSAGES:
  HELP_HEADER: '&a&lCommands:'
  HELP_GENERAL_USEAGE: '&aUse /pvp {toggle|on|off|status} to change/view pvp state.'
  HELP_VIEW_OTHERS: '&aUse /pvp <player> to see another players pvp state.'
  HELP_SET_OTHERS: '&aUse /pvp {toggle|on|off} <player> to set another players pvp state.'
  NO_PLAYER: '&cCould not find a player by the name <parameter>'
  COMMAND_INVALID_PARAMETER: '&c<parameter> is an invalid parameter. {toggle|on|off|status}'
  COMMAND_NO_PERMISSION: '&cYou do not have permission to set others pvp  state.'
  PVP_ALREADY_ON: '&aYou already have pvp on!'
  PVP_ALREADY_OFF: '&aYou already have pvp off!'
  PVP_ALREADY_ON_OTHERS: '&a<parameter> already has pvp on!'
  PVP_ALREADY_OFF_OTHERS: '&a<parameter> already has pvp off!'
  PVP_STATE_ENABLED: '&aYour pvp has been enabled!'
  PVP_STATE_DISABLED: '&aYour pvp has been disabled!'
  PVP_STATE_CHANGED_OTHERS: '&a<parameter> had their pvp state has been changed to <pvpstate>'
  PVP_STATUS: '&aYour pvp is set to <pvpstate>'
  PVP_STATUS_OTHERS: '&a<parameter> has their pvp <pvpstate>'
  PVP_DISABLED: '&cYou have pvp disabled!'
  PVP_DISABLED_OTHERS: '&c<parameter> has pvp disabled!'