main: com.github.aasmus.pvptoggle.PvPToggle
name: PhanaticPvPToggle
version: 1.2
author: legit_craft
description: Plugin that allows players to toggle PvP state
commands:
  pvp:
    description: used to change PvP state.
    usage: /pvp
    permission: phanaticpvptoggle.allow
    permission-message: You don't have the phanaticpvptoggle.allow permission node.
permissions:
  phanaticpvptoggle.allow:
    description: allows player to change pvp state
    default: true
  phanaticpvptoggle.others:
    description: allows player to see other player's pvp state
    default: op
  phanaticpvptoggle.others.set:
    description: allows player to set other players pvp state
    default: op